#!/usr/bin/bash
source venv
export $(cat .env | xargs) &>/dev/null
export $(cat env.services | xargs) &>/dev/null
cd services/ml_service/
pwd
uvicorn features_store:app --reload --port $FEATURES_STORE_PORT --host $APP_HOST