{
 "title": "My dashboard",
 "description": "SPRINT3  project dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_cpu_usage_percent", "legendFormat": "CPU usage, %" },
    { "expr": "app_memory_usage_percent", "legendFormat": "RAM usage, %" }
   ]
  },
  {
   "title": "Использование ресурсов",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 0 },
   "targets": [
    { "expr": "app_cpu_usage_percent", "legendFormat": "CPU usage,%" },
    { "expr": "app_memory_usage_percent", "legendFormat": "RAM usage,%" }
   ]
  },
  {
   "title": "Сетевой траффик",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{handler=\"/recommendations\"}[$__rate_interval]) )",
     "legendFormat": "Запросов в секунду (p/s)"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{}[$__rate_interval]) )/sum(rate(http_request_duration_seconds_count{}[$__rate_interval]) )",
     "legendFormat": "Ср. время исполнения запроса (s)"
    }
   ]
  },
  {
   "title": "Доля offline-рекомендаций",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(app_offline_recs_percent_bucket[3h]))",
     "legendFormat": "Медиана"
    },
    {
     "expr": "histogram_quantile(0.05, rate(app_offline_recs_percent_bucket[3h]))",
     "legendFormat": "Квантиль 5%"
    },
    {
     "expr": "histogram_quantile(0.95, rate(app_offline_recs_percent_bucket[3h]))",
     "legendFormat": "Квантиль 95%"
    }
   ]
  },
  {
   "title": "Распределение рекомендаций",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$D / ($C + $D) * $E", "type": "math" },
    { "expression": "1 - $E", "type": "math" },
    { "expression": "1 - $F - $G", "type": "math" }
   ]
  },
  {
   "title": "ОШИБКИ ПРИЛОЖЕНИЯ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(app_error_exceptions_recservice_total[1d])\r\n",
     "legendFormat": "Всего:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(app_error_exceptions_recstore_total[1d])",
     "legendFormat": "rec_store:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(app_error_exceptions_eventstore_total[1d])",
     "legendFormat": "event_store:"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(app_error_exceptions_featstore_total[1d])",
     "legendFormat": "feature_store:"
    }
   ]
  }
 ]
}